name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-latest"

  steps:
    - name: Clone the repo
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: >-
        dotnet test
        --no-restore
        --no-build
        --configuration Release
        --logger "console;verbosity=normal"
        --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"
        --blame
        --blame-hang-timeout 7m
        --blame-crash
        --results-directory testresults
        --collect "XPlat Code Coverage" -- RunConfiguration.CollectSourceInformation=true

    - name: Upload test results artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        path: testresults/**
