name: Linter Checks

on: [push, pull_request]

jobs:
  check-formatting:
    runs-on: "ubuntu-latest"

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore tools
        run: dotnet tool restore

      - name: Run CSharpier
        run: dotnet csharpier --check .
